<a href="https://colab.research.google.com/github/tejas05in/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TENSORS**

* A torch.Tensor is a multidimensional matrix containing elements of a single data type.
* Similar to Numpy Array, but full of fun things that make them work better on GPU's (vs regular CPU's)
* default data type is float32
* More suitable for deep learning than a numpy array

In [1]:
import torch
import numpy as np

## LISTS

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NUMPY ARRAYS

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.55640328, 0.98155422, 0.36455006, 0.83180522],
       [0.37980353, 0.91538243, 0.25908232, 0.53509467],
       [0.96617955, 0.99418274, 0.35358989, 0.87069516]])

In [9]:
np1.dtype

dtype('float64')

## TENSORS

In [15]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)
tensor_2d.dtype

tensor([[-1.3350,  0.1603, -1.7828, -0.5514],
        [ 0.1067,  0.4940,  2.3834,  1.6885],
        [ 1.0511, -1.4449,  2.9802, -0.2666]])


torch.float32

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create a tensor put of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5564, 0.9816, 0.3646, 0.8318],
        [0.3798, 0.9154, 0.2591, 0.5351],
        [0.9662, 0.9942, 0.3536, 0.8707]], dtype=torch.float64)